package shov.allapis.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFFB90063)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFFFFD9E2)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF3E001D)
val md_theme_light_secondary = Color(color = 0xFF0B6D35)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFF9EF6B0)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF00210B)
val md_theme_light_tertiary = Color(color = 0xFF4F56A9)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFE0E0FF)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF030865)
val md_theme_light_error = Color(color = 0xFFBA1A1A)
val md_theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFFBFFE1)
val md_theme_light_onBackground = Color(color = 0xFF171E00)
val md_theme_light_surface = Color(color = 0xFFFBFFE1)
val md_theme_light_onSurface = Color(color = 0xFF171E00)
val md_theme_light_surfaceVariant = Color(color = 0xFFF2DDE1)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF514347)
val md_theme_light_outline = Color(color = 0xFF837377)
val md_theme_light_inverseOnSurface = Color(color = 0xFFE2FC8B)
val md_theme_light_inverseSurface = Color(color = 0xFF293500)
val md_theme_light_inversePrimary = Color(color = 0xFFFFB1C8)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFFB90063)

val md_theme_dark_primary = Color(color = 0xFFFFB1C8)
val md_theme_dark_onPrimary = Color(color = 0xFF650033)
val md_theme_dark_primaryContainer = Color(color = 0xFF8E004A)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFFFFD9E2)
val md_theme_dark_secondary = Color(color = 0xFF82D996)
val md_theme_dark_onSecondary = Color(color = 0xFF003918)
val md_theme_dark_secondaryContainer = Color(color = 0xFF005226)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFF9EF6B0)
val md_theme_dark_tertiary = Color(color = 0xFFBEC2FF)
val md_theme_dark_onTertiary = Color(color = 0xFF1F2578)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF373E90)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFE0E0FF)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF171E00)
val md_theme_dark_onBackground = Color(color = 0xFFD4ED7E)
val md_theme_dark_surface = Color(color = 0xFF171E00)
val md_theme_dark_onSurface = Color(color = 0xFFD4ED7E)
val md_theme_dark_surfaceVariant = Color(color = 0xFF514347)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFD5C2C6)
val md_theme_dark_outline = Color(color = 0xFF9E8C90)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF171E00)
val md_theme_dark_inverseSurface = Color(color = 0xFFD4ED7E)
val md_theme_dark_inversePrimary = Color(color = 0xFFB90063)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFFFFB1C8)

val seed = Color(color = 0xFFE7007D)
